### ISSUE TITLE
send/@type not reflected into the event or options arguments of InterpreterScriptingContext.send

### ISSUE THREAD

**Issue by mattoshry** [jbeard4/SCION#326]
Using 2.0.0-w3c-ecma branch.

Given:
      <send type="http://www.w3.org/TR/scxml/#BasicHTTPEventProcessor"
        target="http://127.0.0.1:8020/hello.json" event="app.ping" namelist="x y z"/>

      <send type="custom"
        targetexpr="someVar" event="app.ping" namelist="x y z"/>

it's useful (essential) for a custom the scxml.scion.InterpreterScriptingContext impl to be able to receive the send type in order to implement the specific type of send - without having to introspect on the target.

I'm sure this was exposed in SCION 1.0.

**Comment by jbeard4** [comment]
@mattoshry I am going to formalize this into an API which we will officially support. I will follow up with you with more information about this.
