### ISSUE TITLE
Provide a Roadmap

### ISSUE THREAD

**Issue by jonnermut** [jbeard4/SCION#353]
Looking at the github front page, it looks like this project is dead - all the doco is from 2012, and the commits on master are old and far between, and no recent releases.
However, there is obviously activity on other branches.
What's the status of these? Are they usable? When will they be released?
Any insight appreciated.

**Comment by jbeard4** [comment]
Thanks for your feedback.

This project is still alive. Most development has been happening on 2.0.0-w3c-ecma branch. This branch is quite stable. 

The goal is to finish making the 2.0.0 branch compliant with the SCXML test suite, then merge the 2.0.0 branch into master, and publish new releases to npm. This should be completed by the end of April.

If you have any other questions, please don't hesitate to ask.

**Comment by jonnermut** [comment]
Thanks. So if I were to start a new project using SCION you would recommend starting with the 2.0.0-w3c-ecma branch ?

**Comment by jbeard4** [comment]
Yes.
