### ISSUE TITLE
run a state machine in SCXML with SCION

### ISSUE THREAD

**Issue by aldahirSealtiel** [jbeard4/SCION#360]
I would like to know how to run a state machine created in SCXML language using SCION, I hope you can give me an example or explain me how to run a state machine in SCXML.

Thanks for your attention.

**Comment by jbeard4** [comment]
You can find example code here for node and the browser: https://github.com/jbeard4/scion-demos 

Rhino is also supported. If you have any further questions, please don't hesitate to ask.

**Comment by aldahirSealtiel** [comment]
thanks for the reply, but I tried to run this code in SCXML but this has not worked, I hope you can help me, thank you for your attention.

code SCXML:

<?xml version="1.0" encoding= "UTF-8"?>

<scxml xmlns = "http://www.w3.org/2005/07/scxml" version = "1.0" initialstate="ready">
	<state id="ready">
		<onentry>
			<log expr="ready"/>
		</onentry>
		<transition event="watch.start" target="running">
			<log expr="ready to running"/>
		</transition>
	</state>
	<state id="running">
		<onentry>
			<log expr="running"/>
		</onentry>
		<transition event="watch.split" target="paused">
			<log expr="running to paused"/>
		</transition>
		<transition event="watch.stop" target="stopped">
			<log expr="running to stopped"/>
		</transition>
	</state>
	<state id="paused">
		<onentry>
			<log expr="paused"/>
		</onentry>
		<transition event="watch.unsplit" target="running">
			<log expr="paused to running"/>
		</transition>
		<transition event="watch.stop" target="stopped">
			<log expr="paused to stopped"/>
		</transition>
	</state>
	<state id="stopped">
		<onentry>
			<log expr="stopped"/>
		</onentry>
		<transition event="watch.reset" target="ready">
			<log expr="stopped to ready"/>
		</transition>
	</state>

</scxml>


Code html, for execute the state machine:

<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<meta http-equiv="edit-Type" edit="text/html; charset=utf-8" />

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/es5-shim/1.2.4/es5-shim.min.js"></script>
		<script type="text/javascript" src="http://jbeard4.github.com/scxml.js/builds/latest/scxml.js"></script>
		<script type="text/javascript">
			//declare the your statechart model, same as before
			var scion = require=('scion');
			$(document).ready(function(){
				scion.url("maquina1.scxml",function(err,model){
				if(err) throw err;
				
				var interpreter = new scion.SCXML(model);
				interpreter.start();
				})
			});
		</script>
		
	</head>
	<body>
	</body>
</html>
