### ISSUE TITLE
send/invoke

### ISSUE THREAD

**Issue by aksonov** [jbeard4/SCION#371]
I'm trying to integrate SCION with my project, looks like send or invoke is best variant, but i can't override send to call my code, how to do it? How to return values from my code to SCION?

https://github.com/jbeard4/SCION/wiki/Plugin-API-for-SCION-2.0-branch

Is this project alive?

**Comment by jbeard4** [comment]
Still alive. Please elaborate on your use case and I will advise you. Thank you.

**Comment by aksonov** [comment]
I believe my use case is quite common - i need to integrate my app with scxml state flow - i.e. run _my_ code specified within onentry, onexit, etc. and run transition depending from executing of that code. Now I've implement it by using something like 
```
global.run = function(promise, args) {
  // my wrapper that executed given promise and call scion.gen("success", data) or gen("failure", data)
}
```

then within scxml:
```
<onentry><script>run(storage.load, args)</script></onentry>
```

But it pollutes global space (i have to add all my modules there) and looks like hack, maybe is it better way?

**Comment by jbeard4** [comment]
There are a couple of ways to do this. The pattern that I prefer is to pass your APIs to the state machine instance on an explicit `init` event. Something like:

```xml
<scxml>
  <datamodel>
    <data id="api"/>
  </datamodel>
  <state id="initial_default">
    <transition target="idle" event="init">
      <assign location="api" expr="_event.data"/>
    </transition>
  </state>
  <state id="idle"/>
</scxml>
```

Then you can initialize the session by calling:

```js
session.start()
session.gen('init', {run : function(){
  setTimeout( function(){ session.gen('success') }, 10 ); // do something asynchronous and generate success
}})
```

In the future, I may extend platform.eval to make it easier to inject functions into the session context.

Let me know if you have any other questions. If not, feel free to close the issue. Thank you.

**Comment by aksonov** [comment]
Thanks!
