### ISSUE TITLE
The target id parser is a URL parser, not a URI parser

### ISSUE THREAD

**Issue by jchimene** [jbeard4/SCION#377]
This causes issues with the following
```
<state id="example">
	<onentry>
	<script>
<![CDATA[
		var interpreter = this;
		window.onbeforeunload = function(e){
			interpreter.send({"target" : "sfm.sales.popup", "name" : "sfm.event.sales.popup","type" : "","data" : "","origin" : ""},{"delay" : 0, "sendId" : ""});					
  			e.returnValue = "Really?";
			return e.returnValue;
		}
		$("#salesPage").show();
]]>
	</script>
	</onentry>
```
the associated state is defined as follows
```
<state id="sfm.sales.popup">
```
The issue is that the target URI `sfm.sales.popup` doesn't pass the Daring Fireball URL parser.
The intersection of valid DF URL and valid URI is www.*
No valid URI (id attribute) can contain a colon or a forward slash. A URL that passes the DF match either contains a colon, ends in a forward slash, or starts with `www.`

**Comment by jbeard4** [comment]
`<send>` is used for sending events. Why specify an associated state id as a target of send?

**Comment by jbeard4** [comment]
It's also not clear to me that the value of a state id attribute must be a URI.

**Comment by jchimene** [comment]
Thanks for your time.
I'll close the ticket.
