### ISSUE TITLE
Multiple state identifiers in initial attribute not supported

### ISSUE THREAD

**Issue by sradomski** [jbeard4/SCION#390]
When I specify multiple state identifier in the root scxml element via the initial attribute, I do get:

    (node:83390) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unable to locate initial state for composite state: $generated-scxml-0

Having only a single state referenced via its `id` works fine though.

**Comment by jbeard4** [comment]
Thanks for reporting. I will look into this.

**Comment by jbeard4** [comment]
@sradomski Should be fixed in the latest release (4.3.1). Thanks
