### ISSUE TITLE
accessing application context from scxml 

### ISSUE THREAD

**Issue by chrgrd** [jbeard4/SCION#396]
Is is possible to send a websocket message from the scxml document.
something like this: 

`

  <state id="idle">

    <transition event="init" target="state1">

      <script>

        console.log('Transition to state1');

        ws.send("hello world")

      </script>

    </transition>

  </state>
`

Thanks

**Comment by jbeard4** [comment]
Yes. You can make objects in the application context available in the state machine scripting context available through the `hostContext` argument in `model.prepare`. See here for an example:
